/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IGovRequester, IGovRequesterInterface } from "../IGovRequester";

const _abi = [
  {
    inputs: [],
    name: "afterGovGranted",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IGovRequester__factory {
  static readonly abi = _abi;
  static createInterface(): IGovRequesterInterface {
    return new utils.Interface(_abi) as IGovRequesterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGovRequester {
    return new Contract(address, _abi, signerOrProvider) as IGovRequester;
  }
}
